#-*- encoding: utf8 -*-
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from eulerfunc import triangle, ispentagonal, ishexagonal

def solution():
    """
    Bryukh's solution
    """
    for i in xrange(286, 100000):
        tr = triangle(i)
        if ispentagonal(tr) and ishexagonal(tr):
            return tr
    return None


if __name__ == '__main__':
    pass
